version: 2
updates:
  - assignees:
      - "tvogels01"
    directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "pip"
    reviewers:
      - "harrystech/data-eng"
    schedule:
      day: "monday"
      interval: "weekly"
