version: 2

updates:
  - directory: "/"
    ignore:
      - dependency-name: "Sphinx"
    open-pull-requests-limit: 10
    package-ecosystem: "pip"
    reviewers:
      - "harrystech/data-platform"
    schedule:
      interval: "weekly"

  - directory: "/"
    package-ecosystem: "github-actions"
    reviewers:
      - "harrystech/data-platform"
    schedule:
      interval: "weekly"
