version: 2

updates:
  - assignees:
      - "thomas-vogels"
    directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "pip"
    reviewers:
      - "harrystech/data-eng"
    schedule:
      interval: "weekly"

  - assignees:
      - "thomas-vogels"
    directory: "/"
    package-ecosystem: "github-actions"
    reviewers:
      - "harrystech/data-eng"
    schedule:
      interval: "weekly"
