[tool.black]
include = '\.pyi?$'
line-length = 110
target-version = ['py36']

[tool.isort]
default_section = "THIRDPARTY"
include_trailing_comma = true
force_grid_wrap = 0
known_first_party = ["etl"]
line_length = 110
multi_line_output = 3
use_parentheses = true
