#!/bin/sh

. $(git --exec-path)/git-sh-setup # for die
tmpdir=$(mktemp -d commitXXXXXX)
trap "rm -rf $tmpdir" EXIT
git checkout-index --prefix=$tmpdir/ -af
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')
if [ -n "$files" ]; then
    echo "Checking for pep8 violations"
    echo $files | (cd $tmpdir; xargs pep8)
    echo "Checking for outstanding to-dos"
    echo $files | (cd $tmpdir; xargs grep '# XXX') && die Blocking commit because string '# XXX' detected in patch
fi

