Description: |
    Create a Redshift cluster with its subnet group and parameter group.

AWSTemplateFormatVersion: '2010-09-09'


Parameters:

    VpcStackName:
        Description: (required) Name of cloudformation stack with VPC
        Type: String

    MasterUsername:
        Description: (required) User name for the primary user
        Type: String
        AllowedPattern: "([a-z])([a-z]|[0-9])*"

    MasterUserPassword:
        Description: (required) Password for the primary user (with lowercase, uppercase, numbers etc.)
        Type: String
        NoEcho: true

    NodeType:
        Description: (optional) The type of node to be provisioned
        Type: String
        Default: dc2.large
        AllowedValues:
            - dc1.large
            - dc1.8xlarge
            - dc2.large
            - dc2.8xlarge
            - ds2.xlarge
            - ds2.8xlarge

    NumberOfNodes:
        Description: (optional) The number of compute nodes in the cluster
        Type: Number
        Default: 2

    QueryConcurrency:
        Description: (optional) The maximum number of concurrent queries (part of WLM configuration)
        Type: Number
        Default: 5
        MinValue: 2
        MaxValue: 50

    SnapshotIdentifier:
        Description: (optional) The identifier of an existing snapshot (leave empty to skip)
        Type: String
        Default: ""


Conditions:

    IsSingleNodeCluster:
        !Equals [ !Ref "NumberOfNodes", 1 ]

    HasSnapshotIdentifier:
        !Not [ !Equals [ !Ref "SnapshotIdentifier", "" ] ]


Resources:

    RedshiftClusterSubnetGroup:
        Type: "AWS::Redshift::ClusterSubnetGroup"
        Properties:
            Description: "Cross-reference public subnet ID from VPC stack"
            SubnetIds:
                - Fn::ImportValue: !Sub "${VpcStackName}::public-subnet-id"
            Tags:
                - Key: user:sub-project
                  Value: redshift-cluster

    RedshiftClusterParameterGroup:
        Type: "AWS::Redshift::ClusterParameterGroup"
        Properties:
            Description: "Parameter group for Redshift cluster"
            ParameterGroupFamily: "redshift-1.0"
            Parameters:
                - ParameterName: "require_ssl"
                  ParameterValue: "true"
                - ParameterName: "enable_user_activity_logging"
                  ParameterValue: "true"
                - ParameterName: "statement_timeout"
                  ParameterValue: 7200000
                - ParameterName: "wlm_json_configuration"
                  ParameterValue: !Sub "[{ \"query_concurrency\": ${QueryConcurrency} }]"
            Tags:
                - Key: user:sub-project
                  Value: redshift-cluster

    RedshiftEIP:
        Type: "AWS::EC2::EIP"
        Properties:
            Domain: vpc

    RedshiftCluster:
        Type: "AWS::Redshift::Cluster"
        Properties:
            AutomatedSnapshotRetentionPeriod:
                30
            AvailabilityZone:
                Fn::ImportValue: !Sub "${VpcStackName}::vpc-az"
            ClusterParameterGroupName:
                !Ref RedshiftClusterParameterGroup
            ClusterSubnetGroupName:
                !Ref RedshiftClusterSubnetGroup
            DBName:
                "dev"
            ElasticIp:
                !Ref RedshiftEIP
            Encrypted:
                true
            IamRoles:
                - Fn::ImportValue: !Sub "${VpcStackName}::redshift-iam-role"
                - Fn::ImportValue: !Sub "${VpcStackName}::redshift-copy-role"
            MasterUsername:
                !Ref MasterUsername
            MasterUserPassword:
                !Ref MasterUserPassword
            NodeType:
                !Ref NodeType
            ClusterType:
                !If [ "IsSingleNodeCluster", "single-node", "multi-node" ]
            NumberOfNodes:
                !If [ "IsSingleNodeCluster", !Ref "AWS::NoValue", !Ref NumberOfNodes ]
            PubliclyAccessible:
                true
            PreferredMaintenanceWindow:
                "mon:14:10-mon:14:40"
            VpcSecurityGroupIds:
                - Fn::ImportValue: !Sub "${VpcStackName}::redshift-public-sg"
            SnapshotIdentifier:
                !If [ "HasSnapshotIdentifier", !Ref "SnapshotIdentifier", !Ref "AWS::NoValue" ]
            Tags:
                - Key: user:sub-project
                  Value: redshift-cluster

    # Note that an option to set enhanced VPC routing is missing in CloudFormation, so this must be done using the CLI
    # aws redshift modify-cluster --cluster-identifier "[cluster identifier]" --enhanced-vpc-routing

    ClusterAlertTopic:
        Type: AWS::SNS::Topic

    DiskSpaceUsageTooHighAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: "Disk space usage too high"
            AlarmActions:
                - !Ref ClusterAlertTopic
            MetricName: PercentageDiskSpaceUsed
            Namespace: AWS/Redshift
            Statistic: Average
            ComparisonOperator: GreaterThanThreshold
            Threshold: 60
            Period: 300
            EvaluationPeriods: 3
            Dimensions:
                - Name: ClusterIdentifier
                  Value: !Ref RedshiftCluster

    ClusterUnhealthyAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: "Cluster unhealthy"
            AlarmActions:
                - !Ref ClusterAlertTopic
            MetricName: HealthStatus
            Namespace: AWS/Redshift
            Statistic: Minimum
            ComparisonOperator: LessThanThreshold
            Threshold: 1
            Period: 60
            EvaluationPeriods: 3
            Dimensions:
                - Name: ClusterIdentifier
                  Value: !Ref RedshiftCluster


Outputs:

    RedshiftClusterEndpoint:
        Description: PSQL-friendly connection string
        Value: !Sub "postgres://${MasterUsername}@${RedshiftCluster.Endpoint.Address}:${RedshiftCluster.Endpoint.Port}/dev?sslmode=require"

    RedshiftClusterName:
        Description: Used as value for '--cluster-identifier' in AWS CLI
        Value: !Ref RedshiftCluster
        Export:
            Name: !Sub "${AWS::StackName}::cluster-id"

    RedshiftParamterGroupName:
        Description: Used as value for '--parameter-group-name' in AWS CLI
        Value: !Ref RedshiftClusterParameterGroup

    ClusterAlertTopicArn:
        Description: ARN of SNS topic to publish CloudWatch alarms
        Value: !Ref ClusterAlertTopic
