name: Publish Docker image for arthur-etl remote stage

on:
  push:
    branches:
    - master
    - next
  release:
    types:
    - published

jobs:
  build-and-push-image:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker meta information
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}/arthur-etl-remote
        # Use the original tag ref, the SHA1, and versions derived from the tag.
        tags: |
          type=ref,event=tag
          type=ref,event=branch
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{version}}
          type=sha

    - name: Build and push with version tags
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        target: remote
