name: Run tests

on:
  push:
    paths:
    - ".github/workflows/unittest.yaml"
    - "python/**"
    - "requirements.txt"
    - "setup.py"
    - "tests/**"

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout out code
      uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v3.0.11
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-*.txt') }}
    - name: Install dependencies
      run: |-
        python3 -m pip install --upgrade pip==20.3.4
        python3 -m pip install --requirement requirements.txt
        python3 -m pip install --requirement requirements-coverage.txt
        python3 setup.py develop
    - name: Run doctests
      env:
        AWS_DEFAULT_REGION: us-east-1
      run: |-
        python3 -m python.etl.selftest
    - name: Run unittests
      # TODO(tom): Keep increasing coverage so that we can raise the fail-under value.
      run: |-
        coverage3 run -m unittest --verbose
        coverage3 report --fail-under=25 --no-skip-covered --show-missing --skip-empty
