name: Run unit tests

on:
  push:
    paths:
    - ".github/workflows/unittest.yaml"
    - "python/**"
    - "requirements.txt"
    - "setup.py"

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout out code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: |-
        python3 -m pip install --upgrade pip==20.3.4
        python3 -m pip install --requirement requirements.txt
        python3 setup.py develop
    - name: Run doctests
      env:
        AWS_DEFAULT_REGION: us-east-1
      run: |-
        python3 -m python.etl.selftest
